# Generated by Django 4.0.5 on 2022-06-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('genero', models.PositiveSmallIntegerField(choices=[(1, 'Maculino'), (2, 'Femenino'), (3, 'Otro')])),
                ('edad', models.PositiveIntegerField(verbose_name='Edad')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
            ],
        ),
    ]
